### ISSUE TITLE
Kelvin merkle proof provider implementation

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/phoenix-archived#21]
https://github.com/dusk-network/phoenix/blob/plonk/src/db/mod.rs#L51

`Db` currently have a mock implementation. Should perform poseidon instead of Blake2b and `query_level` should work as described here:
https://github.com/dusk-network/phoenix/blob/plonk/src/crypto/merkle.rs#L43

**Comment by CPerezz** [comment]
This was closed https://github.com/dusk-network/kelvin/pull/31 and has no longer to do with Phoenix. 

So closing this.
