### ISSUE TITLE
Add storage of nullifiers, proof and public inputs to DB functionality

### ISSUE THREAD

**Issue by jules** [dusk-network/phoenix-archived#31]

**Comment by CPerezz** [comment]
This now is being discussed on which is the solution to compact this data structures as a `Scalar` so they can be stored inside of the kelvin trees that use Poseidon.

See: https://github.com/dusk-network/documentation/blob/master/DERs/smart-contract-storage-solution.md

This is blocked by https://github.com/dusk-network/kelvin/issues/32

**Comment by CPerezz** [comment]
@julesdesmit can you link the specs where the storage of these fields is required?

**Comment by jules** [comment]
@CPerezz I'm not sure of any specs. I believe these were the fields needed for a syncing peer to be able to verify the incoming blocks though.

**Comment by CPerezz** [comment]
Closing for the time being since the issues about the storage  are addressed in dusk-network/rusk-vm#77
