### ISSUE TITLE
Attempt to create a tx with one output

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/phoenix-archived#35]

**Comment by CPerezz** [comment]
@vlopes11 could you provide some info about this and which was the purpose of doing that?

**Comment by vlopes11** [comment]
This is mostly functional. The tx have the capacity for 2 outputs, but maybe on a specific situation the user may want to generate only one output.

Example A w/ 2 outputs:
* inputs: 100 dusk from alice
* outputs: 70 dusk to bob, 25 dusk to eve, 5 dusk to miner

Example B w/ 1 output:
* inputs: 100 dusk from alice
* outputs: 95 dusk to bob, 5 dusk to miner

Example B was not extensively tested. This issue is to review if everything is fine with that scenario. Should work out of the box, tho.

**Comment by CPerezz** [comment]
Since now @ZER0 and @Bounce23 are the ones working on that, probably it would be a good idea to assign this to them.

**Comment by vlopes11** [comment]
I'm not sure if this still applies since we changed some stuff. Maybe we should close this issue; doesn't seem to be a requirement anymore.

**Comment by CPerezz** [comment]
Closing since this case should not happen.
