### ISSUE TITLE
Update DUSK token contract circuits once encryption gadget is ready

### ISSUE THREAD

**Issue by LukePearson1** [dusk-network/phoenix-archived#78]
Some of the different steps in the DUSK token contract are reliant upon the encryption scheme. These are commented out and written as ///TODO:. They need to be refactored once the encryption gadget is done and merged.

**Comment by CPerezz** [comment]
This doesn't apply since basically we don't have the circuits implemented and therefore there's nothing to Update. 

The circuits need to be implemented in `rusk` from scratch.
